### ISSUE TITLE
Fix Upgrade Images: Upload different manifest to fix org test failing in post upgrade tier tests

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/satellite6-upgrade#112]
Post-Upgrade Tier test 'tests.foreman.ui.test_organization::test_verify_bugzilla_1259248' is failing due to:
```
 Same manifest('robotello-automation') uploaded already in satellite image in Default Organization and hence that cannot be uploaded again during this testrun in another org.
```
Proposed Fix:
```
Remove the existing manifest in images and upload another one but not 'robotello-automation' so later test wont fail while uploading the manifest
```

**Comment by san7ket** [comment]
I think it's better we tweak the test itself , to update manifest in different org and not use default org

**Comment by san7ket** [comment]
I took a look onto this issue and related test-case. The test case uploads a original manifest (with fake certs).
This is because the test requires a manifest refresh which cannot be done using fake manifest.
This fails on the upgrade box because we already have that original manifest uploaded in default org.

Either we need to use a different manifest in default org.
OR create a new manifest for the test's that requires to refresh manifest or needs a original manifest.
@sghai @rochacbruno What can be done here?

**Comment by sghai** [comment]
Instead of uploading the manifest in default_org, can we upload in any other org ? I think that would be the easy solution to fix it or now.

**Comment by san7ket** [comment]
The test is using a different org to upload manifest , but the manifest used in test is original, i.e same as we have uploaded in default org. (Not a fake manifest used by other tests)

**Comment by sghai** [comment]
ah.. got it. I think then only way to fix this issue is to generate a new light manifest(with one or two subscriptions) and use that in test.
