### ISSUE TITLE
Task for Syncing latest capsule repos in Satellite fails on 6.5

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#324]
https://github.com/SatelliteQE/satellite6-upgrade/blob/6cfdfa89bf7fb1d8f226d5d2deaf7a9a2c40adeb/upgrade/helpers/tasks.py#L72
```

INFO:upgrade_logging:Syncing latest capsule repos in Satellite ...
WARNING:nailgun.client:Received HTTP 404 response: {"displayMessage":"One of parameters [ organization_id ] required but not specified.","errors":["One of parameters [ organization_id ] required but not specified."]}
Check if repository is already enabled, else retrigger
WARNING:upgrade_logging:Check if repository is already enabled, else retrigger
```

See job/upgrade-to-6.5-rhel7/108/console

**Comment by devendra104** [comment]
Capsule Sync operation are still falling due to below warning messages
WARNING:nailgun.client:Received HTTP 409 response: {"displayMessage":"The repository is already enabled","errors":["The repository is already enabled"]}
409 Client Error: Conflict for url:
WARNING:upgrade_logging:409 Client Error: Conflict for url:
WARNING:nailgun.client:Received HTTP 500 response: {"displayMessage":"Required lock is already taken by other running tasks.\nPlease inspect their state, fix their errors and resume them.\n\nRequired lock: read\nConflicts with tasks:\n

**Comment by ntkathole** [comment]
Fixed!
