### ISSUE TITLE
Increase the disk space , smoke tests failing due to no space 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#79]
Manjority of the smoke tests are failing due to 
```
Received HTTP 500 response: {
  "error": {"message":"No space left on device @ fptr_finalize - /usr/share/foreman/tmp/cache/template_kind_names20170904-43908-x7cect"}
}
```

**Comment by sghai** [comment]
@san7ket : where to increase the disk space ? Is it on rhevm images ? and required for both rhel6 and rhel7. Moreover, please point the smoke tests those are consuming space ? Is it w/ recent upgrade ?

**Comment by sghai** [comment]
Okay.. It seems an issue w/ only rhel6 rhevm images and w/ end_to_end tests that we enabled for post upgrade tests.

**Comment by sghai** [comment]
@san7ket : Just to summarize:

We are running end_2_end tests post upgrade and from CLI/UI/API. I think we don't need to cover or run from all components. Si lets run api/CLI only.

Also, as images are growing, we need to create the storage on images, may be 15G on satellites only for rhel6 and rhel7.

For now, anyway, we are running e_2_e tests in separate jobs so that won't affect other tests. So either a) run them as is or b) remove them temporarily.

**Comment by san7ket** [comment]
Going with option b) as these tests doesn't affect other tests from robottelo and run under separate job.

**Comment by san7ket** [comment]
Done for RHEL6 and RHEL7 , RHEL7 6.2.z box needs maintenance.

**Comment by san7ket** [comment]
This is done and also the boxes were cleaned , got rid of older versions of CV's , increased memory and storage on both z-streams templates and ran the mongo repair to defrag the db
